name = "Ships Modpack"
author = "flashgnash"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f61b59d1de3ea47688e50891048020ad5acd6e182a42724edd237d2d0472b964"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"
