name = "Ships Modpack"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e23f02a8757627c6b3e9e498538457cadf6f45fbc0ccf6b89cc699815dd4e46"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"
